Using the latest cached version of the dataset since danavery/urbansound8K couldn't be found on the Hugging Face Hub
Found the latest cached dataset configuration 'default' at /scratch/ptolemy/users/kg1623/.cache/huggingface/datasets/danavery___urbansound8_k/default/0.0.0/8aa9177a0c5a6949ee4ee4b7fcabb01dfd4ae466 (last modified on Sat Apr 26 19:45:24 2025).
  0%|          | 0/100 [00:00<?, ?it/s]  1%|          | 1/100 [01:45<2:54:17, 105.63s/it]  2%|▏         | 2/100 [03:28<2:50:00, 104.09s/it]  3%|▎         | 3/100 [05:11<2:47:42, 103.73s/it]  4%|▍         | 4/100 [06:54<2:45:27, 103.42s/it]  5%|▌         | 5/100 [08:37<2:43:31, 103.28s/it]  6%|▌         | 6/100 [10:20<2:41:35, 103.14s/it]  7%|▋         | 7/100 [12:03<2:39:52, 103.15s/it]  8%|▊         | 8/100 [13:46<2:38:01, 103.06s/it]  9%|▉         | 9/100 [15:30<2:36:36, 103.26s/it] 10%|█         | 10/100 [17:12<2:34:27, 102.98s/it] 11%|█         | 11/100 [18:55<2:32:34, 102.86s/it] 12%|█▏        | 12/100 [20:38<2:30:56, 102.92s/it] 13%|█▎        | 13/100 [22:21<2:29:05, 102.82s/it] 14%|█▍        | 14/100 [24:03<2:27:24, 102.84s/it] 15%|█▌        | 15/100 [25:48<2:26:27, 103.39s/it] 16%|█▌        | 16/100 [27:31<2:24:19, 103.09s/it] 17%|█▋        | 17/100 [29:13<2:22:22, 102.92s/it] 18%|█▊        | 18/100 [30:58<2:21:27, 103.50s/it] 18%|█▊        | 18/100 [32:40<2:28:52, 108.93s/it]
/scratch/ptolemy/users/kg1623/projects/deep-learning/audio-classification-using-ViT/venv/lib/python3.10/site-packages/torch/__init__.py:2150: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert condition, message
